language: node_js
node_js:
  - "node"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng e2e
- ng build --prod --base-href https://ericzhou0815.github.io/Angular-Todo-App/
